[package]
name = "host_health_check_api"
version = "0.1.0"
edition = "2024"

[dependencies]
regent-sdk = { path = "../../" }
axum = "0.8.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
chrono = "0.4.43"
