[package]
name = "regent-sdk"
version = "0.1.0"
edition = "2024"
description = "Rust SDK of the Regent project"
license = "Apache-2.0"

[dependencies]
machineid-rs = "1.2.4"
serde = {version = "1.0.215", features= ["derive"]}
serde_yaml = "0.9.33"
serde_json = "1.0.132"
sha2 = "0.10.8"
ssh2 = "0.9.4"
tera = "1.20.0"
pem = { version = "3.0.4", features = ["serde"] }
chrono = "0.4.38"
rayon = "1.10.0"

[profile.release]
lto = true

[lib]
doctest = false
